// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN-uVmkrULQo9YUstZWdApWRmzlwRTlNE',
    appId: '1:274942893578:web:74e4d0dc2daff34b6989f3',
    messagingSenderId: '274942893578',
    projectId: 'greenhand-510fe',
    authDomain: 'greenhand-510fe.firebaseapp.com',
    storageBucket: 'greenhand-510fe.firebasestorage.app',
    measurementId: 'G-ZP36KZXEGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsDA7LBSJ7O7_06zWX9zjNL1BWsa3jvG0',
    appId: '1:274942893578:android:fe956abf684215f46989f3',
    messagingSenderId: '274942893578',
    projectId: 'greenhand-510fe',
    storageBucket: 'greenhand-510fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd8q9DVFT-NcoJTP46ITV2lbuAQwa1Oxk',
    appId: '1:274942893578:ios:4bbe2aa6dcca4c8b6989f3',
    messagingSenderId: '274942893578',
    projectId: 'greenhand-510fe',
    storageBucket: 'greenhand-510fe.firebasestorage.app',
    iosBundleId: 'com.example.greenhand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd8q9DVFT-NcoJTP46ITV2lbuAQwa1Oxk',
    appId: '1:274942893578:ios:4bbe2aa6dcca4c8b6989f3',
    messagingSenderId: '274942893578',
    projectId: 'greenhand-510fe',
    storageBucket: 'greenhand-510fe.firebasestorage.app',
    iosBundleId: 'com.example.greenhand',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN-uVmkrULQo9YUstZWdApWRmzlwRTlNE',
    appId: '1:274942893578:web:874a44958d300d576989f3',
    messagingSenderId: '274942893578',
    projectId: 'greenhand-510fe',
    authDomain: 'greenhand-510fe.firebaseapp.com',
    storageBucket: 'greenhand-510fe.firebasestorage.app',
    measurementId: 'G-7Q1NEC1CXQ',
  );
}
